name = "Scholar"
license = "MIT"
licenselink = "https://github.com/denolteholding/scholar/blob/main/LICENSE"
description = "A Hugo theme for your personal website"
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.56.0"

[author]
  name = "Dennis Nolte"
  homepage = "denolte.com"